version: '3.8'

services:
    db:
        image: cgr.dev/chainguard/postgres:latest-dev
        environment:
            - POSTGRES_USER=${PGUSER}
            - POSTGRES_PASSWORD=${PGPASSWORD}
            - POSTGRES_DB=${PGDATABASE}
            - POSTGRES_HOST=${PGHOST}
        ports:
            - "5432:5432"
        volumes:
            - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db:
